spring:
  application:
    name: team-arbeidsforhold-statistikk
  datasource:
    url: ${PGJDBCURL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          audiences: ${AZURE_APP_CLIENT_ID}
app:
  client:
    id: ${CLIENT_ID:local-test-client}
  private-key: ${PRIVATE_KEY}
