spring:
  application:
    name: team-arbeidsforhold-statistikk
  datasource:
    url: ${PGJDBCURL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
app:
  client:
    id: ${CLIENT_ID:local-test-client}
  private-key: ${PRIVATE_KEY}
logging:
  level:
    org.springframework.core.env: TRACE
