apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: team-arbeidsforhold-statistikk
  namespace: arbeidsforhold
spec:
  ingresses:
    - https://team-arbeidsforhold-statistikk.dev.nav.cloud.nais.io
  port: 8080
  replicas:
    max: 2
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  postgres:
    clusterName: arbeidsforhold-github-app
  env:
    - name: PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: github-app
          key: private-key
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: github-app
          key: client-id
