apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: team-arbeidsforhold-statistikk
  namespace: arbeidsforhold
  labels:
    team: arbeidsforhold
spec:
  ingresses:
    - {{ ingress }}
  port: 8080
  replicas:
    max: 2
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  postgres:
    clusterName: arbeidsforhold-github-app
  envFrom:
    - secret: github-app
  azure:
    application:
      enabled: true
      tenant: {{ azure_tenant }}
      allowAllUsers: false
      claims:
        groups:
          - id: {{ access_group }}
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
    outbound:
      external:
        - host: api.github.com
