apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: team-arbeidsforhold-statistikk
  namespace: arbeidsforhold
  labels:
    team: arbeidsforhold
spec:
  ingresses:
    - https://team-arbeidsforhold-statistikk.ansatt.dev.nav.no
  port: 8080
  replicas:
    max: 2
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  postgres:
    clusterName: arbeidsforhold-github-app
  envFrom:
    - secret: github-app
  azure:
    application:
      enabled: true
      tenant: {{ azure_tenant }}
      allowAllUsers: false
      claims:
        groups:
          - id: "08d977f5-0fba-4079-991f-e392f6e63013"
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"
    sidecar:
      enabled: true
      autoLogin: true
